appName: frontend-app
fullname: frontend-app
replicaCount: 1

image:
  repository: 458266539113.dkr.ecr.eu-central-1.amazonaws.com/soulb-ntt-frontend-dev #TODO: replace to var
  pullPolicy: IfNotPresent
  tag: "soulb-ntt-frontend-114"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
 
securityContext: {}

service:
  enabled: true
  ports:
    http:
      externalPort: 8080
      internalPort: 80
      protocol: TCP

ingress:
  enabled: true
  fqdn: "dev.sbid.io"
  locations:
    "/":
      serviceName: "frontend-app-sv"
      servicePort: 8080
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  extraHosts: {}

  serverSnippets: {}

resources: {} 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
