{{- if .Values.service.enabled -}}
{{- $serviceDefaultName :=  printf "%s-%s" (include "name" .) "sv" -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $serviceDefaultName }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: "NodePort"
  ports:
{{- range $key, $value := .Values.service.ports }}
  - port: {{ default 80 $value.externalPort }}
    targetPort: {{ $value.internalPort }}
    protocol: {{ $value.protocol }}
    name: {{ $key }}
{{- end }}
  selector:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
{{- end -}}
